// vite-plugin-sql-glob.ts
import { readdir, writeFile } from "fs/promises";
import { join, basename } from "path";
import type { Plugin } from "vite";

export function sqlGlobPlugin(): Plugin {
  const VIRTUAL_SUFFIX = "?all";
  const trackedDirs = new Map<string, string>(); // dir → moduleSpecifier

  async function generateDts(dir: string, moduleSpec: string) {
    const files = (await readdir(dir)).filter(f => f.endsWith(".sql"));
    const keys = files.map(f => basename(f, ".sql"));

    const union = keys.length
      ? keys.map(k => JSON.stringify(k)).join(" | ")
      : "string";

    const dtsPath = join(dir, "sql-statements.d.ts");
    await writeFile(
      dtsPath,
      [
        `// Auto-generated by vite-plugin-sql-glob. Do not edit.`,
        `declare module ${JSON.stringify(`*/${moduleSpec}?all`)} {`,
        `  const statements: Record<${union}, string>;`,
        `  export default statements;`,
        `}`,
        ``,
      ].join("\n")
    );
  }

  return {
    name: "vite-plugin-sql-glob",

    async resolveId(id: string, importer: string | undefined) {
      if (!id.endsWith(VIRTUAL_SUFFIX) || !importer) return;
      const moduleSpec = id.slice(0, -VIRTUAL_SUFFIX.length).replace(/^\.\//, "");
      const dir = join(importer, "..", id.slice(0, -VIRTUAL_SUFFIX.length));
      const virtualId = `\0sql-glob:${dir}`;

      if (!trackedDirs.has(dir)) {
        trackedDirs.set(dir, moduleSpec);
        await generateDts(dir, moduleSpec);
      }

      return virtualId;
    },

    async load(id: string) {
      if (!id.startsWith("\0sql-glob:")) return;
      const dir = id.slice("\0sql-glob:".length);

      const files = (await readdir(dir)).filter(f => f.endsWith(".sql"));
      const keys = files.map(f => basename(f, ".sql"));

      const imports = files
        .map((f, i) => `import _${i} from ${JSON.stringify(`${dir}/${f}?raw`)};`)
        .join("\n");

      const entries = keys
        .map((k, i) => `  ${JSON.stringify(k)}: _${i}`)
        .join(",\n");

      return `${imports}\n\nconst statements = {\n${entries}\n};\n\nexport default statements;`;
    },

    configureServer(server) {
      server.watcher.on("add", async path => {
        if (!path.endsWith(".sql")) return;
        const dir = join(path, "..");
        const moduleSpec = trackedDirs.get(dir);
        if (!moduleSpec) return;
        await generateDts(dir, moduleSpec);
        // Invalidate the virtual module so Vite reloads it
        const virtualId = `\0sql-glob:${dir}`;
        const mod = server.moduleGraph.getModuleById(virtualId);
        if (mod) server.moduleGraph.invalidateModule(mod);
        server.ws.send({ type: "full-reload" });
      });

      server.watcher.on("unlink", async path => {
        if (!path.endsWith(".sql")) return;
        const dir = join(path, "..");
        const moduleSpec = trackedDirs.get(dir);
        if (!moduleSpec) return;
        await generateDts(dir, moduleSpec);
        const virtualId = `\0sql-glob:${dir}`;
        const mod = server.moduleGraph.getModuleById(virtualId);
        if (mod) server.moduleGraph.invalidateModule(mod);
        server.ws.send({ type: "full-reload" });
      });
    },
  };
}
