// Auto-generated by vite-plugin-sql-glob. Do not edit.
declare module "*/statements/?all" {
  const statements: Record<"get_statistics" | "insert_query" | "insert_request" | "search_item" | "search_item_body" | "search_item_body_like" | "search_item_like" | "search_user" | "search_user_about" | "search_user_about_like" | "search_user_like" | "select_item" | "select_item_with_comments" | "select_items_with_comments" | "select_raw" | "select_user" | "setup_hn" | "setup_search" | "setup_statistics" | "upsert_item" | "upsert_raw" | "upsert_user", string>;
  export default statements;
}
