// Auto-generated by vite-plugin-sql-glob. Do not edit.
declare module "*/statements/?all" {
  const statements: Record<"search_comment" | "search_comment_like" | "search_story" | "search_story_body" | "search_story_body_like" | "search_story_like" | "search_user" | "search_user_about" | "search_user_about_like" | "search_user_like" | "select_item" | "select_raw" | "select_user" | "setup_hn" | "setup_search" | "sync_search" | "sync_users" | "upsert_item" | "upsert_raw" | "upsert_user", string>;
  export default statements;
}
