// Auto-generated by vite-plugin-sql-glob. Do not edit.
declare module "*/migrations/?all" {
  const statements: Record<"01_add_first_cached_at" | "02_add_top_position" | "03_add_item_change_tracking", string>;
  export default statements;
}
